repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        require_serial: true

    -   id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [python]
        require_serial: true

    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        additional_dependencies:
          - types-PyYAML>=6.0.0